version: "3.8"
name: pedaki
services:
  db:
    image: postgres:13.13
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pedaki}
      POSTGRES_USER: pedaki
      POSTGRES_PASSWORD: pedaki
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./bin/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: "ghcr.io/pedakihq/pedaki:$PEDAKI_TAG"
    depends_on:
      db:
        condition: service_healthy
      caddy:
        condition: service_healthy
    volumes:
      - ./public:/public
      - ./uploads:/uploads

  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    healthcheck:
      test: [ "CMD", "caddy", "version" ]
      timeout: 20s
      retries: 10

